### ISSUE TITLE
How can I number sections below subsection in this template?

### ISSUE THREAD

**Issue by boa-z** [SUEPaper/math201-latex-report#2]
for example:

一、 = section
1.1 = subsection
1.1.1 = subsubsection

I want to know how to modify math201.cls to achieve this function, thanks.

**Comment by HaiwenZhang** [comment]
You can see https://mirrors.ibiblio.org/CTAN/language/chinese/ctex/ctex.pdf page 15 and change line 184, line 199, line 208 in math201.cls. Maybe you can see https://github.com/SUEPaper/ds204-latex-report

**Comment by HaiwenZhang** [comment]
> for example:
> 
> 一、 = section 1.1 = subsection 1.1.1 = subsubsection
> 
> I want to know how to modify math201.cls to achieve this function, thanks.

You can see https://mirrors.ibiblio.org/CTAN/language/chinese/ctex/ctex.pdf page 15 and change line 184, line 199, line 208 in math201.cls. Maybe you can see https://github.com/SUEPaper/ds204-latex-report
